/*

 BACK1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : D:\c++Refresher\GB101\TESTS\backtileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define back1Width 40
#define back1Height 18
#define back1Bank 0

extern const unsigned char back1[];

/* End of BACK1.H */
