/*

 BULLET.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char bulletSprite[] =
{
  0x00,0x00,0x00,0x00,0x7F,0x7F,0xC3,0xFF,
  0x83,0xBF,0xC3,0xCF,0x7F,0x7F,0x00,0x00
};

const unsigned char bulletSprite2[] =
{
   0x18,0x18,0x24,0x24,0x42,0x42,0xC3,0xC3,
  0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF
};
/* End of BULLET.C */
