/*

 SPRITETEST.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char spritename[] =
{
  0x08,0x08,0x06,0x06,0x04,0x04,0x10,0x10,
  0xB0,0xB0,0xF0,0xF0,0xF8,0xF8,0x40,0x40
};

/* End of SPRITETEST.C */
